services: 
  mario:
       build: .
       ports:
         - '80:80'
       container_name: mario-container
       volumes: 
        - myapps3:/usr/share/nginx/html
       network_mode:
          bridge

volumes:
  myapps3:          